#nullable enable

using System.Collections.Generic;

namespace DxfContourStudio.Application.Localization;

/// <summary>
/// en-US resource — an aligned skeleton for UI foundation. Every key present
/// in zh-CN must exist here (enforced by tests); wording is basic but usable.
/// Before any public GitHub release the wording must be audited/completed.
/// </summary>
public static class LocalizedStringsEn
{
    public static IReadOnlyDictionary<string, string> All { get; } = Build();

    private static IReadOnlyDictionary<string, string> Build()
    {
        var d = new Dictionary<string, string>(System.StringComparer.Ordinal)
        {
            ["App.Name"] = "DxfContourStudio Workbench",

            ["Menu.File"] = "File",
            ["Menu.File.Open"] = "Open DXF...",
            ["Menu.File.OpenProject"] = "Open Project...",
            ["Menu.File.Save"] = "Save Project",
            ["Menu.File.SaveAs"] = "Save As...",
            ["Menu.File.Export"] = "Export",
            ["Menu.File.ExportClean"] = "Export Clean DXF...",
            ["Menu.File.Exit"] = "Exit",

            ["Menu.Edit"] = "Edit",
            ["Menu.Edit.Undo"] = "Undo",
            ["Menu.Edit.Redo"] = "Redo",
            ["Menu.Edit.Delete"] = "Delete",
            ["Menu.Edit.SelectAll"] = "Select All",
            ["Menu.Edit.ClearSelection"] = "Clear Selection",

            ["Menu.View"] = "View",
            ["Menu.View.FitAll"] = "Fit All",
            ["Menu.View.ZoomIn"] = "Zoom In",
            ["Menu.View.ZoomOut"] = "Zoom Out",
            ["Menu.View.ShowAllLayers"] = "Show All Layers",
            ["Menu.View.HideAllLayers"] = "Hide All Layers",

            ["Menu.Analyze"] = "Analyze",
            ["Menu.Analyze.Contours"] = "Analyze Contours",
            ["Menu.Analyze.Diagnostics"] = "Contour Diagnostics",

            ["Menu.Tools"] = "Tools",
            ["Menu.Tools.Settings"] = "Settings",
            ["Menu.Tools.Language"] = "Language",
            ["Menu.Tools.Language.ZhCn"] = "简体中文",
            ["Menu.Tools.Language.Us"] = "English",

            ["Menu.Help"] = "Help",
            ["Menu.Help.About"] = "About DxfContourStudio",
            ["About.Text"] = "DxfContourStudio - CAD contour foundation.\n\n.NET 10 / WPF / ACadSharp",

            ["Toolbar.Open"] = "Open",
            ["Toolbar.OpenProject"] = "Open Project",
            ["Toolbar.Save"] = "Save",
            ["Toolbar.SaveProject"] = "Save Project",
            ["Toolbar.ExportClean"] = "Export Clean DXF",
            ["Toolbar.RepairAll"] = "Repair All Safe Gaps",
            ["Toolbar.Undo"] = "Undo",
            ["Toolbar.Redo"] = "Redo",
            ["Toolbar.Select"] = "Select",
            ["Toolbar.Delete"] = "Delete",
            ["Toolbar.FitAll"] = "Fit",
            ["Toolbar.ZoomIn"] = "Zoom In",
            ["Toolbar.ZoomOut"] = "Zoom Out",
            ["Toolbar.Analyze"] = "Analyze",
            ["Toolbar.Repair"] = "Repair Gap",

            ["Tooltip.Open"] = "Open DXF file (Ctrl+O)",
            ["Tooltip.Save"] = "Save project",
            ["Tooltip.Undo"] = "Undo (Ctrl+Z)",
            ["Tooltip.Redo"] = "Redo (Ctrl+Y)",
            ["Tooltip.Delete"] = "Delete selected (Del)",
            ["Tooltip.Select"] = "Select / move entities",
            ["Tooltip.FitAll"] = "Zoom to fit (F)",
            ["Tooltip.ZoomIn"] = "Zoom in",
            ["Tooltip.ZoomOut"] = "Zoom out",
            ["Tooltip.Analyze"] = "Analyze contours: topology, gap diagnostics, hole nesting",
            ["Tooltip.Repair"] = "Repair the selected small gap (undoable)",
            ["Tooltip.ExportClean"] = "Export a cleaned DXF (never overwrites the source)",
            ["Tooltip.RepairAll"] = "Repair all safe gaps (single undo restores all)",

            ["Panel.Layers"] = "Layers",
            ["Panel.Contours"] = "Contours",
            ["Panel.Properties"] = "Properties",
            ["Panel.Diagnostics"] = "Diagnostics",
            ["Panel.Import"] = "Import Report",

            ["Layer.ShowAll"] = "Show All",
            ["Layer.HideAll"] = "Hide All",
            ["Layer.ShowAllTip"] = "Show all layers",
            ["Layer.HideAllTip"] = "Hide all layers",
            ["Layer.Col.Visible"] = "Vis",
            ["Layer.Col.Layer"] = "Layer",
            ["Layer.Col.Count"] = "Count",

            ["Contours.Empty"] = "No contour analysis yet",
            ["Contours.Action"] = "Analyze Contours",
            ["Contours.Total"] = "Contours",
            ["Contours.Closed"] = "Closed",
            ["Contours.Open"] = "Open",
            ["Contours.Outer"] = "Outer",
            ["Contours.Hole"] = "Hole",
            ["Contours.Island"] = "Island",
            ["Contours.GapCount"] = "Small gaps",
            ["Contours.Anomaly"] = "Anomalies",
            ["Contours.Col.Id"] = "Id",
            ["Contours.Col.Summary"] = "Summary",
            ["Contours.Row.Summary"] = "{0} - length {1}",
            ["Contours.Row.Open"] = "open - gap {0}",
            ["Contours.Repair"] = "Repair Gap",
            ["Contours.NextAnomaly"] = "Next Anomaly",
            ["Contours.PrevAnomaly"] = "Previous Anomaly",
            ["Contours.FitToSelection"] = "Fit to selected contour",
            ["Contours.Warning.Open"] = "contour is open",

            ["Diag.Empty"] = "No diagnostics",
            ["Diag.SmallGap"] = "Small gap",
            ["Diag.OpenEnd"] = "Open end",
            ["Diag.Branch"] = "Branch node",
            ["Diag.ZeroLength"] = "Zero-length entity",
            ["Diag.VerySmall"] = "Very small entity",
            ["Diag.Duplicate"] = "Duplicate entity",
            ["Diag.SelfIntersection"] = "Self intersection",
            ["Diag.InvalidGeometry"] = "Invalid geometry (NaN/Infinity)",
            ["Diag.Severity.Info"] = "Info",
            ["Diag.Severity.Warning"] = "Warning",
            ["Diag.Severity.Error"] = "Error",
            ["Diag.Col.Severity"] = "Severity",
            ["Diag.Col.Type"] = "Type",
            ["Diag.Col.Position"] = "Position",
            ["Diag.Col.Distance"] = "Distance",
            ["Diag.Col.Entity"] = "Entity",
            ["Diag.Detail.Gap"] = "distance {0} - repairable",
            ["Diag.Detail.OpenEnd"] = "distance {0} - beyond repair range",
            ["Diag.Detail.NoMatch"] = "no matching endpoint",
            ["Diag.Detail.Branch"] = "branch junction (degree {0})",
            ["Diag.Detail.ZeroLength"] = "length {0} - below zero-length tolerance",
            ["Diag.Detail.VerySmall"] = "length {0} - very small (warning)",
            ["Diag.Detail.Duplicate"] = "#{0} duplicates #{1}",
            ["Diag.Detail.SelfIntersection"] = "#{0} crosses #{1} at the intersection point",
            ["Diag.Collapse"] = "Collapse",
            ["Diag.CollapseTip"] = "Collapse or expand the bottom diagnostics panel",

            ["Viewport.Empty"] = "Click \"Open DXF\" to begin.",

            ["About.Title"] = "About DxfContourStudio",
            ["About.Version"] = "Version",
            ["About.Technology"] = "Technology",
            ["About.Description"] = "DXF contour workbench: topology chaining, contour closing, gap diagnostics and repair.",
            ["About.License"] = "License",
            ["About.GitHub"] = "GitHub",
            ["About.GitHub.NotPublished"] = "Repository not published yet",
            ["About.Copyright"] = "Copyright (c) 2026 DxfContourStudio project",
            ["About.Close"] = "Close",
            ["About.TechStack"] = ".NET 10 / WPF / ACadSharp",
            ["About.LicenseName"] = "MIT",

            ["Props.Empty.Title"] = "No selection",
            ["Props.Empty.Hint"] = "Select an entity in the CAD view to see its properties.",
            ["Props.Group.Basic"] = "General",
            ["Props.Group.Geometry"] = "Geometry",
            ["Props.Group.Bounds"] = "Bounds",
            ["Props.Group.Document"] = "Document",
            ["Props.Group.Multi"] = "Summary",

            ["Property.Id"] = "Id",
            ["Property.Type"] = "Type",
            ["Property.Layer"] = "Layer",
            ["Property.Visible"] = "Visible",
            ["Property.Length"] = "Length",
            ["Property.CenterX"] = "Center X",
            ["Property.CenterY"] = "Center Y",
            ["Property.Radius"] = "Radius",
            ["Property.Diameter"] = "Diameter",
            ["Property.Circumference"] = "Circumference",
            ["Property.StartX"] = "Start X",
            ["Property.StartY"] = "Start Y",
            ["Property.EndX"] = "End X",
            ["Property.EndY"] = "End Y",
            ["Property.StartAngle"] = "Start Angle",
            ["Property.EndAngle"] = "End Angle",
            ["Property.SweepAngle"] = "Sweep Angle",
            ["Property.ArcLength"] = "Arc Length",
            ["Property.Closed"] = "Closed",
            ["Property.Segments"] = "Segment Count",
            ["Property.Yes"] = "Yes",
            ["Property.No"] = "No",

            ["Property.Count"] = "Count",
            ["Property.TotalLength"] = "Total Length",
            ["Property.Types"] = "Types",
            ["Property.LayerList"] = "Layers",

            ["Doc.Entities"] = "Entities",
            ["Doc.Layers"] = "Layers",
            ["Doc.Bounds"] = "Bounds",
            ["Doc.Size"] = "Size",

            ["Type.Line"] = "Line (LINE)",
            ["Type.Circle"] = "Circle (CIRCLE)",
            ["Type.Arc"] = "Arc (ARC)",
            ["Type.Polyline"] = "Lightweight Polyline (LWPOLYLINE)",

            ["Entity.Line"] = "Line (LINE)",
            ["Entity.Arc"] = "Arc (ARC)",
            ["Entity.Circle"] = "Circle (CIRCLE)",
            ["Entity.LwPolyline"] = "Lightweight Polyline (LWPOLYLINE)",
            ["Entity.Polyline"] = "Polyline (POLYLINE)",
            ["Entity.Spline"] = "Spline (SPLINE)",
            ["Entity.Ellipse"] = "Ellipse (ELLIPSE)",
            ["Entity.Insert"] = "Insert (INSERT)",
            ["Entity.TextLike"] = "Text (TEXT/MTEXT)",
            ["Entity.Other"] = "Other",

            ["Unit.Millimeter"] = "Millimeter",
            ["Unit.Inch"] = "Inch",
            ["Unit.Unitless"] = "Unitless",
            ["Unit.Unknown"] = "Unknown",
            ["Unit.Centimeter"] = "Centimeter",
            ["Unit.Meter"] = "Meter",
            ["Unit.Foot"] = "Foot",
            ["Unit.MmAbbr"] = "mm",

            ["Status.X"] = "X",
            ["Status.Y"] = "Y",
            ["Status.Zoom"] = "Zoom",
            ["Status.Unit"] = "Units",
            ["Status.Entities"] = "Entities",
            ["Status.Selected"] = "Selected",

            ["Status.Ready"] = "Ready. Open a DXF file.",
            ["Status.Opened"] = "DXF loaded: {0}",
            ["Status.Summary"] = "Entities {0}, layers {1}",
            ["Status.ImportFailed"] = "Import failed: {0}",
            ["Status.NothingToFit"] = "Nothing to fit",
            ["Status.UndoMove"] = "Undid move",
            ["Status.RedoMove"] = "Redid move",
            ["Status.UndoGeneric"] = "Undid action",
            ["Status.RedoGeneric"] = "Redid action",
            ["Status.Deleted"] = "Deleted {0} entities",
            ["Status.Moved"] = "Moved {0} entities",
            ["Status.Cleared"] = "Selection cleared",
            ["Status.LayerShown"] = "Layer shown: {0}",
            ["Status.LayerHidden"] = "Layer hidden: \"{0}\"",
            ["Status.AllShown"] = "All layers shown",
            ["Status.AllHidden"] = "All layers hidden",
            ["Status.Fit"] = "Fitted to window",
            ["Status.SelectedCount"] = "{0} selected",
            ["Status.Analyzed"] = "Analyzed: {0} contours, {1} closed, {2} open",
            ["Status.AnalyzeFailed"] = "Contour analysis failed, see diagnostic log",
            ["Status.GapRepaired"] = "Repaired {0} small gap(s)",
            ["Status.GapRepairUndone"] = "Gap repair undone",
            ["Status.NoContours"] = "No closed contour found",
            ["Status.AnomalyLocated"] = "Anomaly located: {0}",
            ["Status.BatchRepaired"] = "Repaired {0} gap(s)",
            ["Status.ProjectSaved"] = "Project saved: {0}",
            ["Status.ProjectLoaded"] = "Project loaded: {0}",
            ["Status.ProjectSaveFailed"] = "Project save failed: {0}",
            ["Status.ProjectLoadFailed"] = "Project load failed: {0}",
            ["Status.ExportDone"] = "Exported: {0} ({1} entities)",
            ["Status.ExportFailed"] = "Export failed: {0}",
            ["Status.NothingToSave"] = "Nothing to save yet",
            ["Status.NothingToExport"] = "Nothing to export yet",
            ["Unsaved.Title"] = "Unsaved changes",
            ["Unsaved.Message"] = "The document has unsaved changes. Save before {0}?",
            ["Unsaved.Save"] = "Save",
            ["Unsaved.Discard"] = "Discard",
            ["Unsaved.Cancel"] = "Cancel",
            ["Dialog.ProjectFilter"] = "DxfContourStudio project (*.dxfstudio)|*.dxfstudio|All files (*.*)|*.*",
            ["Dialog.ExportFilter"] = "DXF files (*.dxf)|*.dxf|All files (*.*)|*.*",

            ["Report.File"] = "File",
            ["Report.Version"] = "DXF Version",
            ["Report.DeclaredUnit"] = "Declared Units",
            ["Report.InterpretedUnit"] = "Interpreted Units",
            ["Report.LayerCount"] = "Layers",
            ["Report.TotalEntities"] = "Total Entities",
            ["Report.Imported"] = "Imported",
            ["Report.Ignored"] = "Ignored",
            ["Report.Unsupported"] = "Unsupported",
            ["Report.Warnings"] = "Warnings",
            ["Report.Errors"] = "Errors",
            ["Report.Elapsed"] = "Elapsed",
            ["Report.Empty"] = "No DXF file opened yet",
            ["Report.StatisticsTitle"] = "Entity Statistics",

            ["Command.Later"] = "Coming in a later version",
            ["Common.Yes"] = "Yes",
            ["Common.No"] = "No",
            ["Dialog.DxfFilter"] = "DXF files (*.dxf)|*.dxf|All files (*.*)|*.*",
        };

        return d;
    }
}